### PR TITLE
Add support to customize the scope

### PR DESCRIPTION
**Pull request by mr-menno**
added support for optional scope attribute for #50

### CODE REVIEW

**Comment by mr-menno** [comment]
Other option is to possibly update this PR to make the scope option empty be default and only add it if it has a value.

**Comment by sergiodxa** [comment]
@mr-menno do you think you can add a test for this? a simpler one creating the strategy with a custom scope and check the scope is applied.

**Comment by mr-menno** [comment]
Honestly, I'm not good at writing tests.

**Comment by sergiodxa** [comment]
Support for this was implemented in #89

**Pull request closed without merging**
